### ISSUE TITLE
Is video coming out for this ? 

### ISSUE THREAD

**Issue by MehmetKaranlik** [SwiftfulThinking/SwiftfulRoutingExample#1]
Hey nick!

Is video coming out for this? 
A detailed routing tutorial would be awesome ! 

Thanks.

**Comment by SwiftfulThinking** [comment]
Hey @MehmetKaranlik ... sorry I just saw this. I was waiting to make some major updates for iOS 16, which I did this weekend. I might do a quick video on YT in a few months, but I'm hesitant because I don't think new devs should rely heavily on 3rd-party frameworks while learning. I'm going to close this ticket for now - feel free to reopen if needed.
